// AUTO-GENERATED by tools/gen_device_config.py - DO NOT EDIT BY HAND.
// Lists every SoC whose header lives under freq_control/soc/.
// Re-run tools/gen_device_config.py to update.

#ifndef FREQ_CONTROL_DEVICE_REGISTRY_H_
#define FREQ_CONTROL_DEVICE_REGISTRY_H_

#include <cstdint>

#include "freq_control/soc/s5e9955.h"

namespace freq_control {

enum class Device : uint32_t {
  kS5E9955 = 0,
};

inline constexpr DeviceRegistryEntry kDeviceRegistry[] = {
    {Device::kS5E9955, "s5e9955", &s5e9955::kDeviceConfig},
};

}  // namespace freq_control

#endif  // FREQ_CONTROL_DEVICE_REGISTRY_H_
