// Pin a thread to a CPU cluster using the sched_setaffinity(2) syscall.
//
// These functions complement FreqController: a typical pattern is to boost
// a cluster (e.g. kBig) via FreqController and pin a worker thread to that
// cluster so it actually runs on the boosted CPUs:
//
//     freq_control::FreqController ctl;
//     ctl.SetFrequencyMode(freq_control::FrequencyMode::kBoost);
//     ctl.SetClocks();
//     freq_control::SetThreadAffinity(freq_control::CpuCluster::kBig);
//     /* ... hot loop runs on big cores at boosted clocks ... */
//     freq_control::ResetThreadAffinity();
//     ctl.UnsetClocks();
//
// The cluster -> CPU-id mapping is provided by the per-SoC config header
// (see config/soc/<soc>.h, generated by tools/gen_device_config.py).

#ifndef FREQ_CONTROL_THREAD_AFFINITY_H_
#define FREQ_CONTROL_THREAD_AFFINITY_H_

#include <sys/types.h>

#include "freq_control/device_config.h"

namespace freq_control {

// Pins `tid` to the CPUs belonging to `cluster`. Pass tid == 0 (default) to
// pin the calling thread. Issues a single sched_setaffinity(2) syscall.
// Returns false if the cluster is not declared in the SoC config or if the
// syscall fails (the caller may inspect errno).
bool SetThreadAffinity(CpuCluster cluster, pid_t tid = 0);

// Restores `tid` (or the calling thread) to the union of all clusters
// declared in the SoC config -- effectively "no restriction" relative to
// what the kernel exposes for this SoC.
bool ResetThreadAffinity(pid_t tid = 0);

}  // namespace freq_control

#endif  // FREQ_CONTROL_THREAD_AFFINITY_H_
