// AUTO-GENERATED by tools/gen_device_config.py - DO NOT EDIT BY HAND.
// Regenerate with:
//   tools/gen_device_config.py --adb-serial <SERIAL>

#ifndef FREQ_CONTROL_SOC_S5E9955_H_
#define FREQ_CONTROL_SOC_S5E9955_H_

#include <cstdint>
#include <iterator>

#include "freq_control/device_config.h"

namespace freq_control {
namespace s5e9955 {

// Rail sysfs paths.
inline constexpr char kCpuBigMin[] = "/sys/devices/system/cpu/cpufreq/policy7/scaling_min_freq";
inline constexpr char kCpuBigMax[] = "/sys/devices/system/cpu/cpufreq/policy7/scaling_max_freq";
inline constexpr char kCpuLittleMin[] = "/sys/devices/system/cpu/cpufreq/policy0/scaling_min_freq";
inline constexpr char kCpuLittleMax[] = "/sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq";
inline constexpr char kCpuMidMin[] = "/sys/devices/system/cpu/cpufreq/policy2/scaling_min_freq";
inline constexpr char kCpuMidMax[] = "/sys/devices/system/cpu/cpufreq/policy2/scaling_max_freq";
inline constexpr char kCpuPrimeMin[] = "/sys/devices/system/cpu/cpufreq/policy9/scaling_min_freq";
inline constexpr char kCpuPrimeMax[] = "/sys/devices/system/cpu/cpufreq/policy9/scaling_max_freq";
inline constexpr char kGpuMin[] = "/sys/class/devfreq/22200000.sgpu/min_freq";
inline constexpr char kGpuMax[] = "/sys/class/devfreq/22200000.sgpu/max_freq";
inline constexpr char kMifMin[] = "/sys/class/devfreq/17000010.devfreq_mif/scaling_devfreq_min";
inline constexpr char kMifMax[] = "/sys/class/devfreq/17000010.devfreq_mif/scaling_devfreq_max";

// FrequencyMode::kPowerSave (power_save)
inline constexpr RailTarget kPowerSaveTargets[] = {
    {kCpuLittleMin, kCpuLittleMax, 400000ULL, 1056000ULL},
    {kCpuMidMin, kCpuMidMax, 576000ULL, 1344000ULL},
    {kCpuBigMin, kCpuBigMax, 768000ULL, 1536000ULL},
    {kCpuPrimeMin, kCpuPrimeMax, 768000ULL, 1728000ULL},
    {kGpuMin, kGpuMax, 240000ULL, 509000ULL},
    {kMifMin, kMifMax, 676000ULL, 1539000ULL},
};

inline constexpr Tunable kPowerSaveTunables[] = {
    {"SCHED_COMMON_TARGET_LATENCY", nullptr, 0ULL},
    {"MEM_MO_SCEN_ID_CUSTOMIZED", nullptr, 0ULL},
};

// FrequencyMode::kPerformance (performance)
inline constexpr RailTarget kPerformanceTargets[] = {
    {kCpuLittleMin, kCpuLittleMax, 1805000ULL, 1805000ULL},
    {kCpuMidMin, kCpuMidMax, 2362000ULL, 2362000ULL},
    {kCpuBigMin, kCpuBigMax, 2746000ULL, 2746000ULL},
    {kCpuPrimeMin, kCpuPrimeMax, 3303000ULL, 3303000ULL},
    {kGpuMin, kGpuMax, 999000ULL, 999000ULL},
    {kMifMin, kMifMax, 4780000ULL, 4780000ULL},
};

inline constexpr Tunable kPerformanceTunables[] = {
    {"SCHED_COMMON_TARGET_LATENCY", nullptr, 1ULL},
    {"MEM_MO_SCEN_ID_CUSTOMIZED", nullptr, 0ULL},
};

// FrequencyMode::kBoost (boost)
inline constexpr RailTarget kBoostTargets[] = {
    {kCpuLittleMin, kCpuLittleMax, 1805000ULL, 1805000ULL},
    {kCpuMidMin, kCpuMidMax, 2362000ULL, 2362000ULL},
    {kCpuBigMin, kCpuBigMax, 2746000ULL, 2746000ULL},
    {kCpuPrimeMin, kCpuPrimeMax, 3303000ULL, 3303000ULL},
    {kGpuMin, kGpuMax, 999000ULL, 999000ULL},
    {kMifMin, kMifMax, 4780000ULL, 4780000ULL},
};

inline constexpr Tunable kBoostTunables[] = {
    {"SCHED_COMMON_TARGET_LATENCY", nullptr, 1ULL},
    {"MEM_MO_SCEN_ID_CUSTOMIZED", nullptr, 1ULL},
};

inline constexpr ModeProfile kModes[] = {
    {FrequencyMode::kPowerSave, "power_save", kPowerSaveTargets, std::size(kPowerSaveTargets), kPowerSaveTunables, std::size(kPowerSaveTunables)},
    {FrequencyMode::kPerformance, "performance", kPerformanceTargets, std::size(kPerformanceTargets), kPerformanceTunables, std::size(kPerformanceTunables)},
    {FrequencyMode::kBoost, "boost", kBoostTargets, std::size(kBoostTargets), kBoostTunables, std::size(kBoostTunables)},
};

inline constexpr uint32_t kClusterLittleCpus[] = {
    0u, 1u,
};
inline constexpr uint32_t kClusterMidCpus[] = {
    2u, 3u, 4u, 5u, 6u,
};
inline constexpr uint32_t kClusterBigCpus[] = {
    7u, 8u,
};
inline constexpr uint32_t kClusterPrimeCpus[] = {
    9u,
};

inline constexpr CpuClusterMap kClusters[] = {
    {CpuCluster::kLittle, "little", kClusterLittleCpus, std::size(kClusterLittleCpus)},
    {CpuCluster::kMid, "mid", kClusterMidCpus, std::size(kClusterMidCpus)},
    {CpuCluster::kBig, "big", kClusterBigCpus, std::size(kClusterBigCpus)},
    {CpuCluster::kPrime, "prime", kClusterPrimeCpus, std::size(kClusterPrimeCpus)},
};

inline constexpr DeviceConfig kDeviceConfig = {
    "s5e9955",
    kModes, std::size(kModes),
    nullptr, 0,  // custom profiles (none by default)
    kClusters, std::size(kClusters),
};

}  // namespace s5e9955
}  // namespace freq_control

#endif  // FREQ_CONTROL_SOC_S5E9955_H_
